### ISSUE TITLE
suggestion: different names for the config and opml files

### ISSUE THREAD

**Issue by pcause** [piqoni/matcha#8]
config.yaml isn't a particularly friendly name for the config file.  How about placing it in $XDG_CONFIG_DIRS/matcha/config.yaml by default and allow override on the command like.  Also speficy the opml file name in config and also allow override from command line.

**Comment by piqoni** [comment]
Yes, overriding from the command line of the opml and yaml files is definitely on the roadmap and a great suggestion!

The reason why its located next to the app (current dir) is that since the app doesn't have a GUI (to modify these configs) it has to be in a very visible place and beginner friendly. If we add GUI for the configuration then it will definitely be "somewhere hidden" like XDG_CONFIG_HOME

**Comment by piqoni** [comment]
[Added -c file_path will overwrite default config.yaml configuration file](https://github.com/piqoni/matcha/commit/bfd8ccababa0e178dfa9f49c5b67f1cfb520505a)
[Add -o option to append more feeds through an opml file](https://github.com/piqoni/matcha/commit/64f8acbc097a9d2cdb195a51799d1d8344832911)

Thank you for your suggestions!
